apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-service
  name: node-service
spec:
  ports:
  - port: 2551
    name: p2p
    targetPort: 2551
  - port: 9000
    name: rpc
    targetPort: 9000
  - port: 16180
    targetPort: 16180
    name: udp
    protocol: UDP
  clusterIP: None
  selector:
    app: constellation-app
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: constellation-app
spec:
  serviceName: node-service
  replicas: 5
  updateStrategy:
    type: RollingUpdate
    #rollingUpdate:
    #maxSurge: 5
    #maxUnavailable: 5
  template:
    metadata:
      labels:
        app: constellation-app
    spec:
      containers:
      - name: constellation-app
        image: gcr.io/esoteric-helix-197319/constellationlabs/constellation:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        # TODO: Remove host port, this makes the RPC publicly accessible.
          hostPort: 9000
          name: rpc
        - containerPort: 2551
          hostPort: 2551
          name: p2p
        - containerPort: 16180
          hostPort: 16180
          name: udp
          protocol: UDP
        env:
        - name: AKKA_ACTOR_SYSTEM_NAME
          value: constellation
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_REMOTING_BIND_HOST
          value: "$HOSTNAME"
        - name: AKKA_SEED_NODE_PORT
          value: '2551'
        - name: HTTP_HOST
          value: 0.0.0.0
        - name: HTTP_PORT
          value: '9000'
        readinessProbe:
          httpGet:
            port: 9000
            path: /health
          initialDelaySeconds: 30
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            port: 9000
            path: /health
          initialDelaySeconds: 30
          periodSeconds: 3
